services:
  - type: web
    name: zubdata-flask-scraper
    env: python
    buildCommand: |
      apt-get update && apt-get install -y chromium-browser
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 10000
      - key: CHROME_BIN
        value: /usr/bin/chromium-browser
